/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author yetishbey
 */
public class MasaKapatPanel extends javax.swing.JFrame {

    /**
     * Creates new form MasaKapatPanel
     */
    public MasaKapatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMasaAdi = new javax.swing.JLabel();
        lblAcilisZamani = new javax.swing.JLabel();
        lblGecenSure = new javax.swing.JLabel();
        lblTarife = new javax.swing.JLabel();
        lblMusteri = new javax.swing.JLabel();
        lblKullanimTutari = new javax.swing.JLabel();
        lblAdisyonTutari = new javax.swing.JLabel();
        btnMasaKapat = new javax.swing.JButton();
        btnAdisyonEkle = new javax.swing.JButton();
        btnMasaAktar = new javax.swing.JButton();
        lblToplamTutar = new javax.swing.JLabel();
        lblAdisyonDetayiGoruntule = new javax.swing.JLabel();
        btnIndırımUygula = new javax.swing.JButton();
        btnKismenOdendi = new javax.swing.JButton();
        lblMasaKapat = new javax.swing.JLabel();
        lblIslemler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMasaAdi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMasaAdi.setText("Masa Adı");

        lblAcilisZamani.setText("Açılış Zamanı :");
        lblAcilisZamani.setName(""); // NOI18N

        lblGecenSure.setText("Geçen Süre :");

        lblTarife.setText("Tarife :");

        lblMusteri.setText("Müşteri :");

        lblKullanimTutari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKullanimTutari.setText("Kullanım Tutarı :");

        lblAdisyonTutari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAdisyonTutari.setText("Adisyon Tutarı :");

        btnMasaKapat.setText("Tamamen Ödendi");

        btnAdisyonEkle.setText("Adisyon Ekle");

        btnMasaAktar.setText("Masa Aktar");

        lblToplamTutar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblToplamTutar.setText("Toplam Tutar :");

        lblAdisyonDetayiGoruntule.setForeground(new java.awt.Color(0, 51, 255));
        lblAdisyonDetayiGoruntule.setText("Adisyon Detayı Görüntüle");

        btnIndırımUygula.setText("İndirim uygula");

        btnKismenOdendi.setText("Kısmen Ödendi");

        lblMasaKapat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMasaKapat.setText("Masa Kapat");

        lblIslemler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIslemler.setText("İşlemler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMasaAdi)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGecenSure)
                    .addComponent(lblAcilisZamani)
                    .addComponent(lblMusteri)
                    .addComponent(lblTarife)
                    .addComponent(lblAdisyonTutari)
                    .addComponent(lblToplamTutar)
                    .addComponent(lblKullanimTutari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdisyonDetayiGoruntule)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKismenOdendi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMasaKapat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMasaKapat)
                                .addGap(91, 91, 91)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdisyonEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMasaAktar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIndırımUygula)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIslemler)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMasaAdi)
                .addGap(18, 18, 18)
                .addComponent(lblAcilisZamani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGecenSure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTarife, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMusteri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKullanimTutari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdisyonTutari)
                    .addComponent(lblAdisyonDetayiGoruntule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToplamTutar)
                .addGap(15, 15, 15)
                .addComponent(lblIslemler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdisyonEkle)
                    .addComponent(btnMasaAktar)
                    .addComponent(btnIndırımUygula))
                .addGap(37, 37, 37)
                .addComponent(lblMasaKapat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasaKapat)
                    .addComponent(btnKismenOdendi))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasaKapatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasaKapatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasaKapatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasaKapatPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasaKapatPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdisyonEkle;
    private javax.swing.JButton btnIndırımUygula;
    private javax.swing.JButton btnKismenOdendi;
    private javax.swing.JButton btnMasaAktar;
    private javax.swing.JButton btnMasaKapat;
    private javax.swing.JLabel lblAcilisZamani;
    private javax.swing.JLabel lblAdisyonDetayiGoruntule;
    private javax.swing.JLabel lblAdisyonTutari;
    private javax.swing.JLabel lblGecenSure;
    private javax.swing.JLabel lblIslemler;
    private javax.swing.JLabel lblKullanimTutari;
    private javax.swing.JLabel lblMasaAdi;
    private javax.swing.JLabel lblMasaKapat;
    private javax.swing.JLabel lblMusteri;
    private javax.swing.JLabel lblTarife;
    private javax.swing.JLabel lblToplamTutar;
    // End of variables declaration//GEN-END:variables
}
