/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import model.bilgisayar.Bilgisayar;

/**
 *
 * @author yetishbey
 */
public class MasaBilgisiV extends javax.swing.JPanel {

    /**
     * Creates new form MasaBilgisi
     */
    public MasaBilgisiV() {
        initComponents();
        prgGecenSure.setStringPainted(true);
    }

    public void init(Bilgisayar b){
        lblMasaAdi.setText(b.getMasaAdi());
        if(b.getAcilisSaati()!=null){
            if(b.getSureSiniri()!=0){             
                lblKalanSure.setText(Long.toString(b.getSureSiniri() - b.gecenDakikaHesapla())+" dk");
            }else{
                lblKalanSure.setText("-");
            }
            prgGecenSure.setValue(b.gecenOranHesapla());
            lblGecenSure.setText(b.gecenDakikaHesapla()+" dk");
            lblAcilisSaati.setText(b.getAcilisSaati().getHours()+":"+b.getAcilisSaati().getMinutes());
            lblKullanimUcreti.setText(Float.toString(b.kullanimTutariHesapla())+" TL");
            lblAdisyonTutar.setText(Float.toString(b.adisyonTutariHesapla())+" TL");
            lblToplamTutar.setText((b.adisyonTutariHesapla()+b.kullanimTutariHesapla())+" TL");
        }else{
            lblGecenSure.setText("Kapalı");
            lblKalanSure.setText("-");
            lblAcilisSaati.setText("Kapalı");
            lblKullanimUcreti.setText("-"); 
            lblAdisyonTutar.setText("-");
            lblToplamTutar.setText("-");
            prgGecenSure.setValue(0);
           
        }
        lblKullanici.setText("Kayıtlı Değil");
        if(b.getMusteri() != null)
            lblKullanici.setText(b.getMusteri().getAd());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblMasaAdi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prgGecenSure = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKullanici = new javax.swing.JLabel();
        lblAcilisSaati = new javax.swing.JLabel();
        lblGecenSure = new javax.swing.JLabel();
        lblKalanSure = new javax.swing.JLabel();
        lblAdisyonTutar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblKullanimUcreti = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblToplamTutar = new javax.swing.JLabel();

        jLabel2.setText("Açılış Saati :");

        lblMasaAdi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMasaAdi.setText("Masa - X");

        jLabel5.setText("Kalan Süre :");

        jLabel3.setText("Geçen Süre :");

        jLabel6.setText("Kullanıcı :");

        jLabel4.setText("Adisyon Tutarı :");

        lblKullanici.setText("Kayıtlı Değil");

        lblAcilisSaati.setText("14:20");

        lblGecenSure.setText("5 dk");

        lblKalanSure.setText("-");

        lblAdisyonTutar.setText("-");

        jLabel7.setText("Kullanım Ücreti :");

        lblKullanimUcreti.setText("-");

        jLabel8.setText("Toplam Tutar :");

        lblToplamTutar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblToplamTutar.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKullanimUcreti)
                            .addComponent(lblKullanici)
                            .addComponent(lblAcilisSaati)
                            .addComponent(lblGecenSure)
                            .addComponent(lblKalanSure))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdisyonTutar)
                            .addComponent(lblToplamTutar))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prgGecenSure, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasaAdi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMasaAdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblKullanici))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAcilisSaati))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblGecenSure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblKalanSure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblKullanimUcreti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAdisyonTutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblToplamTutar))
                .addGap(18, 18, 18)
                .addComponent(prgGecenSure, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAcilisSaati;
    private javax.swing.JLabel lblAdisyonTutar;
    private javax.swing.JLabel lblGecenSure;
    private javax.swing.JLabel lblKalanSure;
    private javax.swing.JLabel lblKullanici;
    private javax.swing.JLabel lblKullanimUcreti;
    public javax.swing.JLabel lblMasaAdi;
    private javax.swing.JLabel lblToplamTutar;
    private javax.swing.JProgressBar prgGecenSure;
    // End of variables declaration//GEN-END:variables
}
